name: Bug Report
description: Create a report to help us improve
title: '[Bug]: '
labels: ['bug', 'triage']
assignees:
  - Olyno
body:
  - type: input
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: markdown
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce the bug
      description: |
        Please describe the steps you took to reproduce the bug.
        If you can't reproduce the bug, please describe the steps you took to
        get as close as possible to the bug.
      placeholder: "1. Do something\n2. Do something else"
      validation:
        required: true
  - type: input
    id: except_behavior
    attributes:
      label: Excepted behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: The version of Whirl you're using.
      placeholder: '1.0.0'
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome (or chromium based)
        - Firefox
        - Safari
        - Opera
    validations:
      required: true
  - type: markdown
    id: additional_information
    attributes:
      label: Additional informations
      description: Add any other context about the problem here.
      validation:
        required: false
