name: Build project

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup NodeJS environement
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Load cached dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
                
      - name: Install dependencies
        run: yarn install

      - name: Build Project
        run: yarn build